[[language]]
name = "rust"
rulers = [100]

[language-server.rust-analyzer.config]
check = { command = "clippy", extraArgs = ["--", "-W", "clippy::pedantic"] }

[[language]]
name = "haskell"
auto-format = true

[[language]]
name = "lua"
auto-format = true

[[language]]
name = "c"
auto-format = true
