[[language]]
name = "rust"
rulers = [100]

[language-server.rust-analyzer.config]
check = { command = "clippy", extraArgs = ["--", "-W", "clippy::pedantic"] }

[[language]]
name = "c"
auto-format = true

[[language]]
name = "cpp"
auto-format = true

[[language]]
name = "markdown"
soft-wrap.enable = true
text-width = 80
soft-wrap.wrap-at-text-width = true
