" load sensible defaults first
runtime! plugin/sensible.vim
" load fzf 
set rtp+=/opt/homebrew/opt/fzf
" load the opt lsp plugin
packadd lsp

" show relative line numbers
set relativenumber
" but show the absolute line number for the current line
set number
" case-insensitive search/replace
set ignorecase
" unsless uppercase in search term
set smartcase
" show a column at 80 chars as a guide for long lines
set colorcolumn=80
" show more hidden characters
" also, show tabs nicer
set listchars=tab:^\ ,nbsp:¬,extends:»,precedes:«,trail:•

set termguicolors
colorscheme nord 

let mapleader = " "

noremap <silent> <C-p> :Files<CR>
nnoremap <silent> <leader>; :Buffers<CR>
nnoremap <silent> <leader>w :w<CR>
nnoremap <silent> <leader><leader> <C-^>
nnoremap <silent> <leader>, :set invlist<CR>

" TODO Argument Passing
nnoremap <silent> <leader>wa :LspWorkspaceAddFolder<CR>
nnoremap <silent> <leader>wr :LspWorkspaceRemoveFolder<CR>
nnoremap <silent> <leader>wl :LspWorkspaceListFolders<CR>

nnoremap <silent> gD :LspGotoDeclaration<CR>
nnoremap <silent> gd :LspGotoDefinition<CR>
nnoremap <silent> gt :LspGotoTypeDef<CR>
nnoremap <silent> K :LspHover<CR>
nnoremap <silent> gi :LspGotoImpl<CR>
nnoremap <silent> <leader>r :LspRename<CR>
nnoremap <silent> <leader>a :LspCodeAction<CR>
vnoremap <silent> <leader>a :LspCodeAction<CR>
nnoremap <silent> gr :LspPeekReferences<CR>
nnoremap <silent> <leader>f :LspFormat<CR>
nnoremap <silent> <leader>e :LspDiag current<CR>
nnoremap <silent> [d :LspDiag nextWrap<CR>
nnoremap <silent> ]d :LspDiag prevWrap<CR>
nnoremap <silent> <leader>q :LspDiag show<CR>

" Clangd language server
call LspAddServer([#{
	\    name: 'clangd',
	\    filetype: ['c', 'cpp'],
	\    path: '/opt/homebrew/opt/llvm/bin/clangd',
	\    args: ['--background-index']
	\  }])

" Go language server
call LspAddServer([#{
	\    name: 'golang',
	\    filetype: ['go', 'gomod'],
	\    path: '/opt/homebrew/bin/gopls',
	\    args: ['serve'],
	\    syncInit: v:true
	\  }])

" Rust language server
call LspAddServer([#{
	\    name: 'rustlang',
	\    filetype: ['rust'],
	\    path: '/Users/zibebe/.cargo/bin/rust-analyzer',
	\    args: [],
	\    syncInit: v:true
	\  }]) 
