[colors]
foreground = '#ffffff'
background = '#000000'
cursor_bg = '#ffffff'
cursor_border = '#ffffff'
cursor_fg = '#000000'
selection_bg = '#3c3c3c'
selection_fg = '#ffffff'

ansi = [
  '#000000',
  '#ff8059',
  '#44bc44',
  '#d0bc00',
  '#2fafff',
  '#feacd0',
  '#00d3d0',
  '#bfbfbf'
]
brights = [
  '#595959',
  '#ef8b50',
  '#00c060',
  '#c0c530',
  '#79a8ff',
  '#b6a0ff',
  '#6ae4b9',
  '#ffffff'
]

[colors.tab_bar]
background = "#323232"

[colors.tab_bar.active_tab]
fg_color = "#ffffff"
bg_color = "#0e0e0e"
intensity = "Bold"

[colors.tab_bar.inactive_tab]
fg_color = "#ffffff"
bg_color = "#424242"

[colors.tab_bar.inactive_tab_hover]
fg_color = "#ffffff"
bg_color = "#424242"

[colors.tab_bar.new_tab_hover]
fg_color = "#ffffff"
bg_color = "#323232"
intensity = "Bold"

[colors.tab_bar.new_tab]
fg_color = "#ffffff"
bg_color = "#323232"


[metadata]
name = 'modus-vivendi'
author = 'zibebe'
origin_url = 'https://git.sr.ht/~protesilaos/ef-themes/tree/main/item/modus-vivendi-theme.el'
