[colors]
foreground = '#000000'
background = '#ffffff'
cursor_fg = '#ffffff'
cursor_border = '#000000'
cursor_bg = '#000000'
selection_fg = '#000000'
selection_bg = '#bcbcbc'

ansi = [
  '#000000',
  '#a60000',
  '#005e00',
  '#813e00',
  '#0031a9',
  '#721045',
  '#00538b',
  '#bfbfbf'
]
brights = [
  '#595959',
  '#972500',
  '#145c33',
  '#70480f',
  '#2544bb',
  '#5317ac',
  '#005a5f',
  '#ffffff'
]

[colors.tab_bar]
background = "#d7d7d7"

[colors.tab_bar.active_tab]
fg_color = "#000000"
bg_color = "#f6f6f6"
intensity = "Bold"

[colors.tab_bar.inactive_tab]
fg_color = "#000000"
bg_color = "#b7b7b7"

[colors.tab_bar.inactive_tab_hover]
fg_color = "#000000"
bg_color = "#b7b7b7"

[colors.tab_bar.new_tab_hover]
fg_color = "#000000"
bg_color = "#d7d7d7"
intensity = "Bold"

[colors.tab_bar.new_tab]
fg_color = "#000000"
bg_color = "#d7d7d7"

[metadata]
name = 'modus-operandi'
author = 'zibebe'
origin_url = 'https://git.sr.ht/~protesilaos/ef-themes/tree/main/item/modus-operandi-theme.el'
